# -*- coding: utf-8 -*-
"""ERIA Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DgZZ8fuoOjAy6JHFvbNtBbcYvlDQVOj

# Education Regulation Impact Analaysis

# Install Libraries
"""

!pip install PyPDF2
!pip install pdfplumber
!pip install nltk
!pip install groq
!pip install gensim

import nltk
nltk.download('punkt')
import nltk
nltk.download('punkt_tab')

"""# Data Handling Libraries"""

import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity

import PyPDF2

# List of PDF files (correct way)
pdf_file_paths = [
    "/content/1601817_F.No.-2-25-2024(CPP-II).pdf",
    "/content/3813291_Advisory-Safety-and-Security-of-the-Students.pdf",
    "/content/6493421_UGC-Guidelines-pursuing-two-academic-programmes-simultaneously.pdf",
    "/content/8091137_gazette-antiragging-Second-Amendment.pdf",
    "/content/Notification_9_1-2022-U_3A.pdf",
    "/content/8432142_UGC-Notice-reg.-Erasmus-Programmes.pdf",
    "/content/6579445_Public-Notice-Fake-University.pdf"
]

def extract_text_from_pdf(pdf_path):
    text = ""
    try:
        with open(pdf_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n"
    except Exception as e:
        text = f"Error extracting text: {e}"
    return text

# Extract from all PDFs
all_text = ""

for path in pdf_file_paths:
    print(f"Processing: {path}")
    all_text += extract_text_from_pdf(path) + "\n\n"

print(all_text)

"""# Remove Extra Spaces"""

def remove_whitespace(all_text):
  return  " ".join(all_text.split())

"""# Store Cleaned Text & Print"""

lower_case_sentence = remove_whitespace(all_text)
print(lower_case_sentence)

"""# Tokenizer"""

from nltk import word_tokenize

tokenized_sentences = word_tokenize(lower_case_sentence)
print(tokenized_sentences)

"""# Lower Case"""

text_lower = lower_case_sentence.lower()
print(text_lower)

"""# Punctuation"""

import string
text_no_punct = text_lower.translate(str.maketrans('', '', string.punctuation))
print(text_no_punct)

"""# Stopwords


"""

from nltk.corpus import stopwords # remove stop words
import nltk
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

# Tokenize the text after punctuation removal
clean_tokens = word_tokenize(text_no_punct)

filtered_tokens = [word for word in clean_tokens if word not in stop_words]
print(filtered_tokens)

"""# Stemming"""

from nltk.stem import WordNetstemming
nltk.download('wordnet')

stemmings = WordNetstemming()

Stemming_tokens = [stemmings.steming(word) for word in filtered_tokens]
print(stemming_tokens)

"""# Lemmatizer"""

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
print(lemmatized_tokens)

"""# Word Frequency Analysis"""

from collections import Counter
print(Counter(lemmatized_tokens).most_common(20))

"""# TF-IDF Vectorizer"""

from sklearn.feature_extraction.text import TfidfVectorizer

print(lemmatized_tokens)

"""# Groq Library"""

from groq import Groq
import os

client = Groq(
    api_key="api_key", # Directly passing the API key as a string
)

def analyze_document(text):

    prompt = f"""

    You are an AI assistant that analyzes government and educational documents.

    Return output in this format:

    1. Summary (simple English)
    2. Stakeholders (who is affected: students, teachers, admin, government, etc.)

    Document:
    {text}
    """

    response = client.chat.completions.create(
        model="openai/gpt-oss-safeguard-20b", # Updated to a currently supported model
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return response.choices[0].message.content

all_text_truncated = all_text[:25000]  # Further truncating the text to fit within the model's token limit
result = analyze_document(all_text_truncated)
print(result)

def analyze_document(text):

    client = Groq(
        api_key="api_key", # Directly passing the API key as a string
    )

    prompt = f"""
        You are an AI document analysis expert.

        Analyze the given document and provide a structured response in simple English.

        IDENTIFY THE CATEGORIES AND DISPLAY IT:
        1.Accreditation
        2.Scholarship
        3.Curriculam
        4.Faculty
        5.Policy
        6.Examination
        7.Admissions

        Impact ANALYZER:
        Extract implications for:
        1.Students
        2.Faculty
        3.Administrators
        4.Institutions
        5.Accrediation / Compliance teams

        SENTIMENT & RISK DETECTION:
        Identify:
        1.Controversial areas
        2.Potential implementation issues
        3.Institutional readiness challenges

        Return the output in this format:

        1. Summary (short and clear)
        2.Identify the categories and display it
        3. Stakeholders
         (● Which stakeholders benefit
          ● Which stakeholders face constraints
          ● New academic or institutional opportunities)
        3. Impact Assessment
         (● Short term ((immediate effects in schools, colleges, administration)
          ● Medium term (Growth + stability)
          ● Long term ((future effects over time))
        4. Impact Analyzer
        5.Awareness & Academic Support
        6.Risks (possible problems, challenges, or negative effects)
        7.Positive and Negative
        8.Governance & Compliance

        Document:
        {text}
        """

    response = client.chat.completions.create(
            model="openai/gpt-oss-safeguard-20b", # Corrected model name
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

    return response.choices[0].message.content

all_text_truncated = all_text[:25000] # Truncating the text to fit within the model's token limit
result = analyze_document(all_text_truncated)
print(result)

!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

!pip install groq

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import PyPDF2
# from groq import Groq
# from google.colab import userdata
# # GROQ_API_KEY=userdata.get('GROQ_API_KEY')
# GROQ_API_KEY= "api_key"
# # 🔑 Groq API
# client = Groq(api_key=GROQ_API_KEY)
# 
# # 📄 Extract text from PDF
# def extract_text(pdf_file):
#     reader = PyPDF2.PdfReader(pdf_file)
#     text = ""
#     for page in reader.pages:
#         page_text = page.extract_text()
#         if page_text:
#             text += page_text + "\n"
#     return text
# 
# # 🤖 AI Analysis Function
# def analyze_document(text):
# 
#     prompt = f"""
#     You are an AI document analysis expert.
# 
#     Provide:
# 
#     1. Summary (short and clear)
#         2.Identify the categories and display it
#         3. Stakeholders
#          (● Which stakeholders benefit
#           ● Which stakeholders face constraints
#           ● New academic or institutional opportunities)
#         3. Impact Assessment
#          (● Short term ((immediate effects in schools, colleges, administration)
#           ● Medium term (Growth + stability)
#           ● Long term ((future effects over time))
#         4. Impact Analyzer
#         5.Awareness & Academic Support
#         6.Risks (possible problems, challenges, or negative effects)
#         7.Positive and Negative
#         8.Governance & Compliance
# 
#     Document:
#     {text}
#     """
# 
#     response = client.chat.completions.create(
#         model="openai/gpt-oss-safeguard-20b",
#         messages=[{"role": "user", "content": prompt}]
#     )
# 
#     return response.choices[0].message.content
# 
# 
# # 🎯 STREAMLIT UI
# st.title("📄 AI PDF Document Analyzer")
# st.write("Upload a PDF to get AI-powered analysis")
# 
# uploaded_file = st.file_uploader("Upload PDF", type=["pdf"])
# 
# if uploaded_file is not None:
# 
#     st.success("PDF Uploaded Successfully!")
# 
#     # Extract text
#     text = extract_text(uploaded_file)
# 
#     if st.button("Analyze Document 🚀"):
# 
#         with st.spinner("Analyzing with AI..."):
#             result = analyze_document(text)
# 
#         st.subheader("📊 Analysis Result")
#         st.write(result)

from google.colab import userdata
GROQ_API_KEY=userdata.get('GROQ_API_KEY')

GROQ_API_KEY

!streamlit run /content/app.py &>/content/logs.txt &

!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# PyPDF2
# Groq